export const SET_LOADING = 'SET_LOADING'
export const GET_LOADING = 'GET_LOADING'
export const SET_PROJECTS = 'SET_PROJECTS'
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID'
export const SET_TASKS = 'SET_TASKS'
export const GET_TASKS = 'GET_TASKS'
export const GET_TASK_BY_ID = 'GET_TASK_BY_ID'
